import { Metadata } from "next";
import Button from "@/components/ui/Button";
import Badge from "@/components/ui/Badge";
import {
  generateServiceSchema,
  generateBreadcrumbSchema,
  generateFAQPageSchema,
} from "@/lib/jsonLd";
import { siteMetadata, ogDefaults } from "@/data/siteMetadata";
import { FAQ } from "@/types";

export const metadata: Metadata = {
  title: "GenZ Asks AI, Not Google. Make AI Recommend Your SaaS. | AEO + SEO + GEO Sprint",
  description:
    "GenZ doesn't search anymore. They ask ChatGPT, Perplexity, Gemini. We control what AI tells them about your SaaS, so AI sends them straight to your product.",
  keywords: [
    "AEO for SaaS",
    "SEO for SaaS startups",
    "GEO services",
    "answer engine optimization",
    "generative engine optimization",
    "AI search optimization",
    "get cited by ChatGPT",
    "Perplexity citations",
    "Google AI Overviews ranking",
    "SaaS SEO agency",
  ],
  openGraph: {
    ...ogDefaults("/aeo-seo-for-saas/"),
    images: ["/images/og-default.png"],
    title: "GenZ Asks AI, Not Google. Make AI Recommend Your SaaS.",
    description:
      "GenZ asks AI. We control what AI tells them about your SaaS, so AI sends them straight to your product.",
  },
  alternates: {
    canonical: `${siteMetadata.url}/aeo-seo-for-saas/`,
  },
};

const engines = [
  { name: "ChatGPT", glyph: "GPT" },
  { name: "Perplexity", glyph: "PX" },
  { name: "Gemini", glyph: "G" },
  { name: "Claude", glyph: "C" },
  { name: "AI Overviews", glyph: "AI" },
  { name: "You.com", glyph: "Y" },
];

const threeMotions = [
  {
    label: "SEO",
    headline: "Rank in blue links.",
    line: "Google search results. Still the foundation.",
    icon: "🔍",
  },
  {
    label: "AEO",
    headline: "Get cited as the answer.",
    line: "Perplexity, ChatGPT with search, You.com.",
    icon: "💬",
  },
  {
    label: "GEO",
    headline: "Be in the generated answer.",
    line: "Gemini, AI Overviews, Claude, free ChatGPT.",
    icon: "✨",
  },
];

const sprintDeliverables = [
  { num: "01", title: "Technical Audit", line: "End-to-end. Indexing, SSR, Core Web Vitals, schema." },
  { num: "02", title: "Schema Markup", line: "Organization, FAQ, Article, Service. Validated." },
  { num: "03", title: "AEO + GEO Setup", line: "llms.txt, markdown alternates, answer blocks, E-E-A-T." },
  { num: "04", title: "Keyword Strategy", line: "Buyer-intent map. Pillar + cluster architecture." },
  { num: "05", title: "Content Production", line: "Pillars and clusters. Your voice. Humans, not slop." },
  { num: "06", title: "On-Page Fixes", line: "Meta, OG, canonical, images, internal linking." },
  { num: "07", title: "IndexNow + AI Bots", line: "Instant indexing. Bot allowlists. Search Console wired." },
  { num: "08", title: "Handover", line: "90-day roadmap. Team trained. Optional retainer." },
];

const whoFor = [
  { tag: "Series A or B SaaS", line: "Has PMF. Ready to scale organic." },
  { tag: "Bootstrapped USD 50k+ MRR", line: "Profitable. Done with retainers." },
  { tag: "Technical pre-PMF", line: "Founder builds. Wants the foundation right." },
  { tag: "Rebrand or reposition", line: "New ICP. Preserve equity. AEO from day one." },
];

const steps = [
  { num: "01", title: "Discovery call", line: "30 min. No pitch." },
  { num: "02", title: "Scoped in 48h", line: "Written scope and timeline." },
  { num: "03", title: "6-week sprint", line: "Shipped to your site, weekly." },
  { num: "04", title: "Handover", line: "Roadmap. Trained team." },
];

const stats = [
  { value: "6", unit: "weeks", label: "End-to-end sprint" },
  { value: "8", unit: "deliverables", label: "Shipped, not slides" },
  { value: "3", unit: "search motions", label: "SEO, AEO, GEO" },
  { value: "48", unit: "hours", label: "To a written scope" },
];

const faqItems: FAQ[] = [
  {
    question: "What is AEO and how is it different from SEO?",
    answer:
      "AEO (Answer Engine Optimization) is the discipline of optimizing content to be cited as the answer by AI search engines like Perplexity, ChatGPT with search, and You.com. SEO optimizes for the traditional Google blue links. AEO optimizes for being quoted. We do both.",
    category: "automation",
    categoryLabel: "Automation",
  },
  {
    question: "What is GEO and why does it matter for SaaS?",
    answer:
      "GEO (Generative Engine Optimization) gets your brand mentioned in answers generated by AI engines that do not cite sources: Gemini, Claude, free ChatGPT, Google AI Overviews. SaaS buyers increasingly start evaluation in these tools. If competitors get mentioned and you do not, you miss the top of the funnel.",
    category: "automation",
    categoryLabel: "Automation",
  },
  {
    question: "How long until I see results?",
    answer:
      "Technical SEO wins show up in Search Console within 2 to 6 weeks. AEO and GEO citations typically appear in 4 to 12 weeks. Content-driven rankings follow the normal SEO curve. The point is a foundation that compounds for 12 to 24 months.",
    category: "automation",
    categoryLabel: "Automation",
  },
  {
    question: "Do I need both AEO and GEO if I already do SEO?",
    answer:
      "Yes. Roughly 25 to 40 percent of buyer-intent searches now flow through some form of AI search engine, and that share grows every quarter. A SaaS that ranks #1 in Google but is never cited by ChatGPT loses an increasing share of the funnel.",
    category: "automation",
    categoryLabel: "Automation",
  },
  {
    question: "What kind of SaaS fits this sprint?",
    answer:
      "Series A or B SaaS, bootstrapped SaaS at USD 50k+ MRR, technical pre-PMF startups setting the foundation, and SaaS in a rebrand. Not the best fit for B2C consumer apps or pure paid-acquisition motions with no organic plan.",
    category: "automation",
    categoryLabel: "Automation",
  },
  {
    question: "Will you produce the content or do we?",
    answer:
      "We produce the content. Pillar pages, cluster posts, rewrites, schema-rich FAQs. Written by humans, edited by humans, in your brand voice. You approve every piece before it goes live.",
    category: "automation",
    categoryLabel: "Automation",
  },
  {
    question: "Do you offer ongoing execution after the sprint?",
    answer:
      "Optional. After the sprint, customers typically pick: keep us on a retainer, hire a dedicated developer or content engineer to embed, or run the roadmap internally. The sprint leaves you with something you can extend independently.",
    category: "automation",
    categoryLabel: "Automation",
  },
  {
    question: "How is this different from hiring an SEO agency?",
    answer:
      "Most SEO agencies sell monthly retainers with vague deliverables. We sell a fixed-scope 6-week sprint that ships measurable improvements end to end. You own the outcomes at the end. No 12-month contract, no monthly busywork.",
    category: "automation",
    categoryLabel: "Automation",
  },
];

export default function AeoSeoForSaasPage() {
  const serviceSchema = generateServiceSchema(
    "AEO, SEO and GEO Sprint for SaaS Startups",
    "Done-for-you 6-week sprint covering AEO, SEO, and GEO for SaaS startups.",
    `${siteMetadata.url}/aeo-seo-for-saas/`
  );

  const breadcrumbSchema = generateBreadcrumbSchema([
    { name: "Home", url: siteMetadata.url },
    { name: "AEO, SEO & GEO for SaaS", url: `${siteMetadata.url}/aeo-seo-for-saas/` },
  ]);

  const faqSchema = generateFAQPageSchema(faqItems);

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />

      {/* HERO */}
      <section className="relative overflow-hidden bg-gradient-to-br from-dark-900 via-dark-800 to-primary-900 dark:from-dark-900 dark:via-dark-900 dark:to-dark-800 pt-32 pb-20 md:pt-40 md:pb-32">
        <div aria-hidden className="absolute inset-0 opacity-30">
          <div className="absolute top-20 left-10 w-72 h-72 bg-primary-500 rounded-full mix-blend-screen filter blur-3xl animate-pulse" />
          <div className="absolute bottom-20 right-10 w-96 h-96 bg-primary-400 rounded-full mix-blend-screen filter blur-3xl animate-pulse" style={{ animationDelay: "1s" }} />
        </div>
        <div className="container-custom relative max-w-5xl text-center">
          <Badge variant="primary" className="mb-6 bg-primary-500/20 text-primary-200 border-primary-400/30">
            AEO · SEO · GEO FOR SAAS
          </Badge>
          <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-extrabold text-white leading-[1.05] tracking-tight">
            GenZ doesn&apos;t Google.
            <br />
            <span className="bg-gradient-to-r from-primary-300 via-primary-400 to-primary-200 bg-clip-text text-transparent">
              They ask AI.
            </span>
          </h1>
          <p className="mt-8 text-lg md:text-2xl text-primary-100/90 max-w-2xl mx-auto leading-relaxed">
            We make AI recommend <span className="text-white font-bold">your SaaS</span> and send buyers straight to your product.
          </p>

          {/* Engine chips */}
          <div className="mt-10 flex flex-wrap justify-center gap-2 md:gap-3">
            {engines.map((e) => (
              <div key={e.name} className="px-4 py-2 rounded-full bg-white/10 backdrop-blur-sm border border-white/20 text-white text-sm font-medium flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-primary-500/40 flex items-center justify-center text-xs font-bold">{e.glyph}</span>
                {e.name}
              </div>
            ))}
          </div>

          <div className="mt-12 flex flex-col sm:flex-row justify-center gap-4">
            <Button href="/contact/" size="lg">Book a discovery call</Button>
            <Button href="#sprint" variant="outline" size="lg" className="!bg-white/10 !border-white/30 !text-white hover:!bg-white/20 hover:!text-white">
              See the sprint
            </Button>
          </div>
        </div>
      </section>

      {/* STATS STRIP */}
      <section className="bg-white dark:bg-dark-900 border-b border-dark-50 dark:border-dark-800">
        <div className="container-custom">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 py-12">
            {stats.map((s) => (
              <div key={s.label} className="text-center">
                <div className="flex items-baseline justify-center gap-1">
                  <span className="text-4xl md:text-5xl font-extrabold text-primary-500">{s.value}</span>
                  <span className="text-sm font-bold text-dark-400">{s.unit}</span>
                </div>
                <p className="mt-2 text-xs md:text-sm text-dark-500 dark:text-dark-300 font-medium uppercase tracking-wide">{s.label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* THE NEW BUYER JOURNEY */}
      <section className="section-padding bg-white dark:bg-dark-900">
        <div className="container-custom max-w-6xl">
          <div className="text-center mb-12">
            <p className="text-sm font-bold text-primary-500 uppercase tracking-widest mb-3">The new buyer journey</p>
            <h2 className="text-3xl md:text-5xl font-extrabold text-dark-900 dark:text-dark-50 leading-tight">
              They ask AI. AI answers.
              <br />
              <span className="text-primary-500">We control the answer.</span>
            </h2>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-center">
            {/* Chat mockup */}
            <div className="relative">
              <div className="rounded-2xl bg-gradient-to-br from-dark-900 to-dark-800 p-6 shadow-2xl border border-dark-700">
                {/* Header */}
                <div className="flex items-center gap-2 pb-4 border-b border-dark-700">
                  <div className="w-2 h-2 rounded-full bg-red-400" />
                  <div className="w-2 h-2 rounded-full bg-yellow-400" />
                  <div className="w-2 h-2 rounded-full bg-green-400" />
                  <p className="ml-3 text-xs text-dark-400 font-medium">ChatGPT</p>
                </div>

                {/* User bubble */}
                <div className="mt-6 flex justify-end">
                  <div className="max-w-[80%] px-4 py-3 rounded-2xl rounded-br-sm bg-primary-500 text-white text-sm">
                    What&apos;s the best tool for [your category]?
                  </div>
                </div>

                {/* AI bubble */}
                <div className="mt-4 flex">
                  <div className="w-8 h-8 rounded-full bg-gradient-to-br from-primary-400 to-primary-600 flex items-center justify-center text-xs font-bold text-white flex-shrink-0">
                    AI
                  </div>
                  <div className="ml-3 max-w-[85%] px-4 py-3 rounded-2xl rounded-bl-sm bg-dark-700 text-dark-100 text-sm leading-relaxed">
                    <p>
                      For SaaS teams like yours, the top option is{" "}
                      <span className="text-primary-300 font-bold underline decoration-primary-400 decoration-2 underline-offset-2">
                        Your Product
                      </span>
                      . It is built for [their use case] and is used by [their persona].
                    </p>
                    <p className="mt-2 text-xs text-dark-400">
                      → yourproduct.com
                    </p>
                  </div>
                </div>

                {/* Cursor blink */}
                <div className="mt-6 flex items-center gap-2 text-dark-500 text-xs">
                  <div className="w-1 h-3 bg-primary-400 animate-pulse" />
                  <span>Typing...</span>
                </div>
              </div>

              {/* Glow */}
              <div aria-hidden className="absolute -inset-4 bg-gradient-to-r from-primary-500/20 to-primary-400/20 blur-2xl -z-10" />
            </div>

            {/* Side text */}
            <div className="space-y-6">
              <div className="flex gap-4">
                <div className="flex-shrink-0 w-12 h-12 rounded-xl bg-primary-50 dark:bg-primary-500/10 text-primary-500 flex items-center justify-center text-xl font-extrabold">
                  1
                </div>
                <div>
                  <h3 className="text-xl font-extrabold text-dark-900 dark:text-dark-50">A buyer asks AI.</h3>
                  <p className="mt-1 text-dark-500 dark:text-dark-300">
                    Not Google. ChatGPT, Perplexity, Gemini.
                  </p>
                </div>
              </div>

              <div className="flex gap-4">
                <div className="flex-shrink-0 w-12 h-12 rounded-xl bg-primary-50 dark:bg-primary-500/10 text-primary-500 flex items-center justify-center text-xl font-extrabold">
                  2
                </div>
                <div>
                  <h3 className="text-xl font-extrabold text-dark-900 dark:text-dark-50">AI gives one answer.</h3>
                  <p className="mt-1 text-dark-500 dark:text-dark-300">
                    Usually one or two products. Not ten blue links.
                  </p>
                </div>
              </div>

              <div className="flex gap-4">
                <div className="flex-shrink-0 w-12 h-12 rounded-xl bg-primary-50 dark:bg-primary-500/10 text-primary-500 flex items-center justify-center text-xl font-extrabold">
                  3
                </div>
                <div>
                  <h3 className="text-xl font-extrabold text-dark-900 dark:text-dark-50">We make it your answer.</h3>
                  <p className="mt-1 text-dark-500 dark:text-dark-300">
                    Schema, citations, entity signals, llms.txt. AI starts recommending you.
                  </p>
                </div>
              </div>

              <div className="pt-2">
                <Button href="/contact/" size="lg">Get on the AI&apos;s shortlist</Button>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* THREE MOTIONS */}
      <section className="section-padding bg-gradient-to-b from-white to-primary-50/30 dark:from-dark-900 dark:to-dark-800">
        <div className="container-custom max-w-6xl">
          <div className="text-center mb-16">
            <p className="text-sm font-bold text-primary-500 uppercase tracking-widest mb-3">Search is now three motions</p>
            <h2 className="text-3xl md:text-5xl font-extrabold text-dark-900 dark:text-dark-50 leading-tight">
              SEO. AEO. GEO.
            </h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {threeMotions.map((m) => (
              <div
                key={m.label}
                className="group relative p-8 rounded-2xl bg-white dark:bg-dark-900 border border-dark-100 dark:border-dark-700 hover:border-primary-300 dark:hover:border-primary-500 hover:shadow-2xl transition-all duration-300"
              >
                <div className="absolute -top-4 -right-4 w-16 h-16 rounded-2xl bg-gradient-to-br from-primary-400 to-primary-600 flex items-center justify-center text-3xl shadow-lg group-hover:scale-110 transition-transform">
                  {m.icon}
                </div>
                <p className="text-xs font-bold text-primary-500 uppercase tracking-widest">{m.label}</p>
                <h3 className="mt-3 text-2xl font-extrabold text-dark-900 dark:text-dark-50 leading-tight">{m.headline}</h3>
                <p className="mt-4 text-sm text-dark-500 dark:text-dark-300 leading-relaxed">{m.line}</p>
                <div className="mt-6 h-1 w-12 bg-gradient-to-r from-primary-400 to-primary-600 rounded-full group-hover:w-24 transition-all duration-300" />
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* SPRINT DELIVERABLES BENTO */}
      <section id="sprint" className="section-padding bg-dark-900 dark:bg-dark-950 text-white">
        <div className="container-custom max-w-6xl">
          <div className="text-center mb-16">
            <p className="text-sm font-bold text-primary-400 uppercase tracking-widest mb-3">6 weeks. End to end.</p>
            <h2 className="text-3xl md:text-5xl font-extrabold leading-tight">
              What you get shipped.
            </h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            {sprintDeliverables.map((d) => (
              <div
                key={d.num}
                className="group p-6 rounded-2xl bg-gradient-to-br from-dark-800 to-dark-900 border border-dark-700 hover:border-primary-500/50 hover:from-primary-900/30 hover:to-dark-900 transition-all duration-300"
              >
                <div className="text-xs font-bold text-primary-400">{d.num}</div>
                <h3 className="mt-3 text-lg font-extrabold text-white">{d.title}</h3>
                <p className="mt-2 text-sm text-dark-300 leading-relaxed">{d.line}</p>
              </div>
            ))}
          </div>
          <div className="mt-12 text-center">
            <Button href="/contact/" size="lg">Scope your sprint</Button>
          </div>
        </div>
      </section>

      {/* WHO FOR */}
      <section className="section-padding bg-primary-50/50 dark:bg-dark-800">
        <div className="container-custom max-w-5xl">
          <div className="text-center mb-12">
            <p className="text-sm font-bold text-primary-500 uppercase tracking-widest mb-3">Best-fit SaaS</p>
            <h2 className="text-3xl md:text-5xl font-extrabold text-dark-900 dark:text-dark-50 leading-tight">
              Built for these teams.
            </h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {whoFor.map((w) => (
              <div
                key={w.tag}
                className="flex items-start gap-4 p-6 rounded-xl bg-white dark:bg-dark-900 border border-dark-50 dark:border-dark-700 hover:shadow-card transition-all"
              >
                <div className="w-3 h-3 mt-2 rounded-full bg-primary-500 flex-shrink-0" />
                <div>
                  <h3 className="font-extrabold text-dark-900 dark:text-dark-50">{w.tag}</h3>
                  <p className="mt-1 text-sm text-dark-500 dark:text-dark-300">{w.line}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* PROCESS visual timeline */}
      <section className="section-padding bg-white dark:bg-dark-900">
        <div className="container-custom max-w-6xl">
          <div className="text-center mb-16">
            <p className="text-sm font-bold text-primary-500 uppercase tracking-widest mb-3">How it works</p>
            <h2 className="text-3xl md:text-5xl font-extrabold text-dark-900 dark:text-dark-50 leading-tight">
              Four steps. No fluff.
            </h2>
          </div>
          <div className="relative grid grid-cols-1 md:grid-cols-4 gap-8">
            {/* connecting line */}
            <div aria-hidden className="hidden md:block absolute top-8 left-[12.5%] right-[12.5%] h-0.5 bg-gradient-to-r from-primary-300 via-primary-500 to-primary-300" />
            {steps.map((s) => (
              <div key={s.num} className="relative text-center">
                <div className="relative z-10 inline-flex items-center justify-center w-16 h-16 rounded-full bg-gradient-to-br from-primary-400 to-primary-600 text-white font-extrabold text-xl shadow-lg shadow-primary-500/30">
                  {s.num}
                </div>
                <h3 className="mt-4 font-extrabold text-dark-900 dark:text-dark-50">{s.title}</h3>
                <p className="mt-1 text-sm text-dark-500 dark:text-dark-300">{s.line}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="section-padding bg-primary-50/30 dark:bg-dark-800">
        <div className="container-custom max-w-3xl">
          <div className="text-center mb-12">
            <p className="text-sm font-bold text-primary-500 uppercase tracking-widest mb-3">FAQ</p>
            <h2 className="text-3xl md:text-5xl font-extrabold text-dark-900 dark:text-dark-50 leading-tight">
              Quick answers.
            </h2>
          </div>
          <div className="space-y-3">
            {faqItems.map((faq) => (
              <details
                key={faq.question}
                className="group p-6 rounded-xl bg-white dark:bg-dark-900 border border-dark-50 dark:border-dark-700 hover:border-primary-300 dark:hover:border-primary-500/50 transition-all"
              >
                <summary className="flex items-center justify-between cursor-pointer list-none">
                  <h3 className="font-bold text-dark-900 dark:text-dark-50 pr-4">{faq.question}</h3>
                  <span className="flex-shrink-0 w-8 h-8 rounded-full bg-primary-50 dark:bg-dark-800 text-primary-500 flex items-center justify-center font-bold group-open:rotate-45 transition-transform">
                    +
                  </span>
                </summary>
                <p className="mt-4 text-dark-600 dark:text-dark-200 leading-relaxed">{faq.answer}</p>
              </details>
            ))}
          </div>
        </div>
      </section>

      {/* FINAL CTA */}
      <section className="relative overflow-hidden section-padding bg-gradient-to-br from-primary-600 via-primary-500 to-primary-700">
        <div aria-hidden className="absolute inset-0 opacity-20">
          <div className="absolute top-0 left-1/4 w-96 h-96 bg-white rounded-full mix-blend-overlay filter blur-3xl" />
          <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-primary-200 rounded-full mix-blend-overlay filter blur-3xl" />
        </div>
        <div className="container-custom relative text-center max-w-3xl">
          <h2 className="text-3xl md:text-5xl font-extrabold text-white mb-4 leading-tight">
            Be the SaaS AI recommends.
          </h2>
          <p className="text-lg text-primary-50 mb-8">
            Tell us about your SaaS. Scoped proposal in 48 hours.
          </p>
          <Button href="/contact/" variant="white" size="lg">Book a discovery call</Button>
        </div>
      </section>
    </>
  );
}
