#!/bin/bash
# IndexNow Submission Script
# Run after deployment to notify search engines of updated URLs
# Usage: ./scripts/indexnow-submit.sh

INDEXNOW_KEY="3e7d2156eff697e75f5a5ec5c33a98e4"
HOST="wfnext.com"
KEY_LOCATION="https://${HOST}/${INDEXNOW_KEY}.txt"

# All site URLs
URLS=(
  "https://${HOST}/"
  "https://${HOST}/hire/ai-developers/"
  "https://${HOST}/hire/data-engineers/"
  "https://${HOST}/hire/frontend-engineers/"
  "https://${HOST}/hire/backend-engineers/"
  "https://${HOST}/hire/product-engineers/"
  "https://${HOST}/hire/vibe-code-engineer/"
  "https://${HOST}/hire/cloud-cost-engineer/"
  "https://${HOST}/hire/qa-testers/"
  "https://${HOST}/hire/langchain-developers/"
  "https://${HOST}/hire/rag-developers/"
  "https://${HOST}/hire/fastapi-developers/"
  "https://${HOST}/hire/fullstack-developers/"
  "https://${HOST}/hire/devops-engineers/"
  "https://${HOST}/hire/mcp-developers/"
  "https://${HOST}/hire/fractional-project-manager/"
  "https://${HOST}/hire/unity-developers/"
  "https://${HOST}/hire/ios-developers/"
  "https://${HOST}/hire/android-developers/"
  "https://${HOST}/hire/nodejs-developers/"
  "https://${HOST}/hire/python-developers/"
  "https://${HOST}/hire/php-developers/"
  "https://${HOST}/hire/java-developers/"
  "https://${HOST}/hire/wordpress-developers/"
  "https://${HOST}/hire/shopify-developers/"
  "https://${HOST}/hire/flutter-developers/"
  "https://${HOST}/hire/react-native-developers/"
  "https://${HOST}/hire/aws-developers/"
  "https://${HOST}/hire/software-engineers/"
  "https://${HOST}/hire/software-architects/"
  "https://${HOST}/hire/generative-ai-developers/"
  "https://${HOST}/hire/computer-vision-developers/"
  "https://${HOST}/hire/chatbot-developers/"
  "https://${HOST}/hire/nlp-developers/"
  "https://${HOST}/hire/mlops-engineers/"
  "https://${HOST}/hire/automation-consultants/"
  "https://${HOST}/consulting/it-consulting/"
  "https://${HOST}/consulting/scalability-consulting/"
  "https://${HOST}/consulting/mvp-consulting/"
  "https://${HOST}/blog/automate-staffing-agency-with-n8n-case-study-2026/"
  "https://${HOST}/blog/recruiter-admin-cost-calculator-2026/"
  "https://${HOST}/blog/10-workflows-every-staffing-agency-should-automate-2026/"
  "https://${HOST}/blog/automate-bullhorn-with-n8n-staffing-agency-guide/"
  "https://${HOST}/blog/bullhorn-jobadder-crelate-automation-comparison-2026/"
  "https://${HOST}/blog/ai-workflow-automation-fleet-companies-2026/"
  "https://${HOST}/blog/hr-document-automation-small-business-2026/"
  "https://${HOST}/blog/saas-web-application-development-guide-startups-2026/"
  "https://${HOST}/blog/best-tech-stack-saas-mvp-2026/"
  "https://${HOST}/blog/securing-rag-applications-data-isolation-patterns-2026/"
  "https://${HOST}/blog/ai-code-review-security-enterprise-pipelines-2026/"
  "https://${HOST}/for/founders/"
  "https://${HOST}/for/startups/"
  "https://${HOST}/for/enterprise/"
  "https://${HOST}/for/europe/"
  "https://${HOST}/for/usa-canada/"
  "https://${HOST}/for/australia/"
  "https://${HOST}/for/dubai/"
  "https://${HOST}/products/seth-ai-recruiter/"
  "https://${HOST}/aeo-seo-for-saas/"
  "https://${HOST}/ai-sdr-outreach/"
  "https://${HOST}/ai-developers-who-build-ai/"
  "https://${HOST}/hire-data-analysts-engineers/"
  "https://${HOST}/ai-agent-hr-recruiting/"
  "https://${HOST}/blog/ai-agent-vs-hiring-human-how-to-decide/"
  "https://${HOST}/blog/what-is-aeo-why-every-saas-needs-it-now/"
  "https://${HOST}/blog/ai-agents-vs-automation-vs-workflows/"
  "https://${HOST}/blog/how-to-choose-tech-stack-for-saas/"
  "https://${HOST}/how-we-work/"
  "https://${HOST}/why-teams-stay/"
  "https://${HOST}/india-handled/"
  "https://${HOST}/about/"
  "https://${HOST}/about/gaurav/"
  "https://${HOST}/faq/"
  "https://${HOST}/contact/"
  "https://${HOST}/careers/"
  "https://${HOST}/privacy-policy/"
  "https://${HOST}/terms-of-use/"
  # Blog listing
  "https://${HOST}/blog/"
  # Blog posts
  "https://${HOST}/blog/12-parameters-ai-matching-tools-should-evaluate/"
  "https://${HOST}/blog/how-does-ai-developer-matching-actually-work/"
  "https://${HOST}/blog/best-ai-developer-matching-tools-2026/"
  "https://${HOST}/blog/what-is-lifestyle-fit-matching-in-developer-hiring/"
  "https://${HOST}/blog/why-offshore-developers-keep-leaving/"
  "https://${HOST}/blog/vibe-coding-explained-when-to-use-it/"
  "https://${HOST}/blog/context-first-matching-why-tech-stack-is-not-enough/"
  "https://${HOST}/blog/real-cost-of-switching-tech-partners/"
  "https://${HOST}/blog/how-to-build-ai-mvp-4-weeks-offshore-developer/"
  "https://${HOST}/blog/dedicated-developer-vs-freelancer-vs-agency-total-cost/"
  "https://${HOST}/blog/ai-developer-interview-questions-what-to-ask/"
  "https://${HOST}/blog/rag-vs-fine-tuning-when-to-use-which/"
  "https://${HOST}/blog/how-to-choose-ai-agent-framework/"
  "https://${HOST}/blog/do-you-still-need-a-prompt-engineer-in-2026/"
  "https://${HOST}/blog/best-workflow-automation-tools-2026/"
  "https://${HOST}/blog/ai-mvp-tech-stack-2026/"
  "https://${HOST}/blog/staff-augmentation-vs-eor-vs-india-entity-2026/"
  "https://${HOST}/blog/toptal-vs-andela-vs-turing-vs-workforcenext-comparison-2026/"
  "https://${HOST}/blog/senior-indian-developer-salary-2026/"
  "https://${HOST}/blog/verify-indian-developer-experience-checklist-2026/"
  "https://${HOST}/blog/most-outsourced-developers-us-companies-2026/"
  "https://${HOST}/blog/mcp-explained-how-to-hire-mcp-developers/"
  "https://${HOST}/blog/kotlin-vs-java-android-2026/"
  "https://${HOST}/blog/hire-software-testing-team-2026/"
  "https://${HOST}/blog/short-term-indian-developers-european-projects-2026/"
  "https://${HOST}/blog/android-app-developer-hiring-guide-2026/"
  "https://${HOST}/blog/hire-nodejs-developers-from-india-2026/"
  "https://${HOST}/blog/hire-reactjs-developers-from-india-2026/"
  "https://${HOST}/blog/hire-mobile-app-developers-cross-platform-2026/"
  "https://${HOST}/blog/hire-remote-mobile-app-testing-team-2026/"
  "https://${HOST}/blog/owasp-llm-top-10-implementation-checklist-2026/"
  "https://${HOST}/blog/prompt-injection-defense-production-llm-apps-2026/"
  "https://${HOST}/blog/nodejs-developer-role-enterprise-applications-2026/"
  "https://${HOST}/blog/nodejs-vs-java-vs-go-enterprise-backend-2026/"
  "https://${HOST}/blog/nodejs-microservices-architecture-enterprise-guide-2026/"
  "https://${HOST}/blog/nodejs-performance-scaling-production-checklist-2026/"
  "https://${HOST}/blog/nodejs-security-enterprise-checklist-owasp-2026/"
  "https://${HOST}/blog/expressjs-vs-fastify-vs-nestjs-2026/"
  "https://${HOST}/blog/enterprise-web-application-development-complete-guide-2026/"
  "https://${HOST}/blog/outsource-enterprise-web-application-development-2026/"
  "https://${HOST}/blog/ai-enabled-remote-staffing-complete-guide-2026/"
)

# Build JSON payload
URL_LIST=""
for url in "${URLS[@]}"; do
  URL_LIST="${URL_LIST}\"${url}\","
done
URL_LIST="[${URL_LIST%,}]"

PAYLOAD="{\"host\":\"${HOST}\",\"key\":\"${INDEXNOW_KEY}\",\"keyLocation\":\"${KEY_LOCATION}\",\"urlList\":${URL_LIST}}"

echo "[IndexNow] Submitting ${#URLS[@]} URLs..."

# Submit to IndexNow API (covers Bing, Yandex, Seznam, Naver)
ENGINES=("https://api.indexnow.org/indexnow" "https://www.bing.com/indexnow" "https://yandex.com/indexnow")

for engine in "${ENGINES[@]}"; do
  echo -n "[IndexNow] ${engine}... "
  HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
    -X POST "${engine}" \
    -H "Content-Type: application/json; charset=utf-8" \
    -d "${PAYLOAD}")
  echo "HTTP ${HTTP_CODE}"
done

echo "[IndexNow] Done. ${#URLS[@]} URLs submitted to ${#ENGINES[@]} engines."
